<?php
function DNAmodule_menu() {
  $items['DNA'] = array(
    'title' => 'Swap Your DNA',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('DNA_form'),
    'access callback' => TRUE,
    'type' => MENU_NORMAL_ITEM,
  );
  $items['DNA-Success'] = array(
    'title' => 'Results',
    'page callback' => 'DNA_results',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );
  return $items;
}

//makes form with input fields and submit
function DNA_form() {
  $form['helix'] = array(
    '#title' => t('Helix'),
    '#type' => 'textfield',
    '#description' => t('Enter your strand of DNA- it can be any combination of A T C G'),
    // '#element_validate' => array('element_validate_helix'),
    '#required' => TRUE,
  );
  $form ['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Swap my DNA!'),
  );
  return $form;
}

function DNA_form_submit($form, &$form_state) {
    $DNA_array = array(
      'A' => 'T',
      'C' => 'G',
      'T' => 'A',
      'G' => 'C',);

    $input = $form_state['values']['helix'];

    $input = strtoupper($input);
    $input_array = str_split($input);
    $output = '';
    foreach($input_array as $input_letter){
      $input_letter_index = array_search($input_letter, $DNA_array);
      $output .= $DNA_array($input_letter[$value]);
    }

  $_SESSION['user_input'] = $input;
  $_SESSION['output'] = $output;

  $form_state['redirect'] = "DNA-Success";
}


function DNA_results() {
  $input = $_SESSION['user_input'];
  $output = $_SESSION['output'];
  return "<strong> Your input was: </strong>" . $input[0] . "</br> <strong>The flipside of your DNA is: </strong>" . $output;
}

// function element_validate_helix($element) {
//   if(preg_match('/[^ACGT ]/', $element['#value'])) {
//     form_error($element, t('You must use only the letters A T C G'));
//   }
// }
